### ISSUE TITLE
About "train_fine_18unlabel_pseudo_TTA_1t_deeplabv3.txt" file 

### ISSUE THREAD

**Issue by daeunni** [jianlong-yuan/SimpleBaseline#8]
Hi, 
Thanks for your nice work. 
Btw, I'm trying to run this code with cityscapes dataset.  
According to your sample .yaml file, cityscapes uses `train_18unlabel_deeplabv3_1t` split. (like below) 

```
DATASET:
    NAME: "cityscape"
    MEAN: [0.5, 0.5, 0.5]
    STD: [0.5, 0.5, 0.5]
    MODE: 'testval'
    SEMI:
        TRAIN_SPLIT_L: 'train_18unlabel_deeplabv3_1t'    # split 
        TRAIN_SPLIT_U: 'train_18unlabel_deeplabv3_1t'    # split 
        VAL_SPLIT: 'val_fine'
```
However, in the `SimpleBaseline/segmentron/data/dataloader/cityscapes.py` L42 we need  **train_fine_18unlabel_pseudo_TTA_1t_deeplabv3.txt** file. 

```
        elif split == 'train_18unlabel_deeplabv3_1t':
            _split_f = [
                        "data/train_fine_18unlabel_pseudo_TTA_1t_deeplabv3.txt",
                        "data/train_fine_18label.txt"]
```

Where can I find this file?

**Comment by daeunni** [comment]
Or can I replace this part like below? 
I want to set semi-supervised setting. 

```
DATASET:
    NAME: "cityscape"
    MEAN: [0.5, 0.5, 0.5]
    STD: [0.5, 0.5, 0.5]
    MODE: 'testval'
    SEMI:
        # DE :: modified
        TRAIN_SPLIT_L: 'train_18label'
        TRAIN_SPLIT_U: 'train_18unlabel'
        VAL_SPLIT: 'val_fine'
```
